services:
  postgres:
    image: postgres:16
    container_name: postgresDB
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_CONF_SHARED_PRELOAD_LIBRARIES: pldebugger
    networks:
      - net_postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PSW}
    ports:
      - "8083:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - net_postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  net_postgres: