spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SERVER_DB_PROD}
    username: ${SERVER_USER}
    password: ${SERVER_PASSWORD}

especializacion:
  url:
    base-imagenes:
  ruta:
    imagenes: ${VOL_MOUNT_IMAGENES}
    imagenes-vacantes: ${VOL_MOUNT_VACANTES}
    documentos: ${VOL_MOUNT_DOCUMENTOS}

