server:
  port: 3333
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    include-message: always
spring:
  application.name: especializacion
  profiles:
    active: dev, security-enabled
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    jdbc:
      dialect: postgresql
  datasource:
#    driver-class-name: org.postgresql.Driver
    url: ${SERVER_URL}
    username: ${SERVER_USER}
    password: ${SERVER_PASSWORD}
  mvc:
  #    throw-exception-if-no-handler-found: true  REVISAR
  web:
    resources:
      static-locations:
        file:${especializacion.ruta.imagenes-vacantes}/

  mail:
    host: mail.unimag.com
    port: 587
    username: correo@unimag.com
    password: mypswd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        orm:
          jpa: DEBUG
        transaction: TRACE

smspropio:
  api:
    url: https://www.smspropio.co/api
    key: mypswd
app:
  mail:
    from-name: Nombre correo

especializacion:
  ruta:
    imagenes: C:/especializacion/imagenes
    imagenes-vacantes: C:/especializacion/imagenes/vacantes
    documentos: C:/especializacion/documentos

