spring:
  application:
    name: espeUnimag
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active:
      - dev
      - security-enabled
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations:
        - "file:${especializacion.ruta.imagenes-vacantes}/"
        - "file:${especializacion.ruta.imagenes}/"

server:
  port: 3333
  servlet:
    context-path: "/"
  error:
    whitelabel:
      enabled: false
    include-message: always

logging:
  level:
    "org.hibernate.SQL": DEBUG
    "org.hibernate.type.descriptor.sql": TRACE
    "org.springframework.orm.jpa": DEBUG
    "org.springframework.transaction": TRACE

smspropio:
  api:
    url: ${SMS_URL}
    key: ${SMS_KEY}

app:
  mail:
    from-name: ${MAIL_FORM_NAME}
